"""Bake source-PNG alpha bounds for readable and GPU-only UI textures alike.

Requires Pillow. Run after replacing artwork; use --check in validation/CI.
Reference/Blank images remain full sprites because their callers disable trimming.
"""
import argparse
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "Assets/Scripts/Chess/Gameplay/UI/MenuArtworkBounds.cs"
FOLDERS = ("Gacha_menu", "PlayerProfile", "LANUI", "MultiplayerUI")


def generate():
    lines = [
        "// Generated by tools/generate_menu_artwork_bounds.py. Do not hand edit.",
        "using System.Collections.Generic;", "using UnityEngine;", "",
        "public static class MenuArtworkBounds", "{",
        "    private static readonly Dictionary<string, Vector4> Bounds = new Dictionary<string, Vector4>",
        "    {",
    ]
    count = 0
    for folder in FOLDERS:
        for path in sorted((ROOT / "Assets/Materials" / folder).glob("*.png")):
            with Image.open(path) as source:
                image = source.convert("RGBA")
                width, height = image.size
                bounds = image.getchannel("A").point(lambda a: 255 if a > 8 else 0).getbbox()
            if not bounds:
                continue
            left, top, right, bottom = bounds
            normalized = (left / width, (height - bottom) / height,
                          (right - left) / width, (bottom - top) / height)
            values = ", ".join(f"{value:.9f}f" for value in normalized)
            key = path.relative_to(ROOT).as_posix()
            lines.append(f'        {{ "{key}", new Vector4({values}) }},')
            count += 1
    lines += [
        "    };", "",
        "    public static Rect GetRect(string path, Texture2D texture)", "    {",
        "        if (!Bounds.TryGetValue(path, out Vector4 b)) return new Rect(0, 0, texture.width, texture.height);",
        "        return new Rect(b.x * texture.width, b.y * texture.height, b.z * texture.width, b.w * texture.height);",
        "    }", "}",
    ]
    return "\n".join(lines) + "\n", count


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if baked geometry no longer matches source PNGs.")
    args = parser.parse_args()
    generated, count = generate()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != generated:
            raise SystemExit("Artwork bounds are stale. Run tools/generate_menu_artwork_bounds.py.")
        print(f"PASS: {count} source PNG bounds match the runtime geometry catalog.")
    else:
        OUTPUT.write_text(generated, encoding="utf-8")
        print(f"Generated bounds for {count} PNGs: {OUTPUT}")


if __name__ == "__main__":
    main()
