using ChessButWeird.Application;
using ChessButWeird.Domain;
int checks=0;
void Check(bool value,string name){if(!value)throw new Exception(name);checks++;Console.WriteLine("PASS "+name);}
var s=new MatchStatistics();
s.AddLocal(Team.Black,"a2-a1",false,null);int revision=s.Revision;
s.ReviseLastMove("a2-a1=Q");
Check(s.Revision>revision&&s.Entries.Single().Text=="a2-a1=Q","Promotion revises existing entry without changing count");
s.AddLocal(Team.Black,"b7-b5",false,null);
Check(s.Entries.All(e=>e.Actor==Team.Black),"Extra owner turn does not alternate sides");
s.AddEvent(Team.White,"Pawn removed at e4");
Check(s.MoveCount==2&&!s.CapturedBy(Team.White).Any(),"Destruction event is not an ordinary capture or a move");
s.AddEvent(Team.Black,"Loot crate captured a Rook",PieceKind.Rook);
Check(s.MoveCount==2&&s.ConfirmedMoveNumber==2&&s.CapturedBy(Team.Black).Single()==PieceKind.Rook,"Ability capture records material without adding a move");
s.Reset();s.AddLocal(Team.White,"exd5",true,PieceKind.Pawn);s.RejectPending();
Check(s.Entries.Count==0&&!s.CapturedBy(Team.White).Any(),"Rejected prediction rolls back notation and captures together");
s.AddLocal(Team.White,"e2-e4",true,null);s.Confirm(1,Team.White,"e4",null,true);s.Confirm(1,Team.White,"e4",null,true);
Check(s.MoveCount==1&&!s.Entries[0].Pending&&s.Entries[0].Text=="e4","Server confirmation replaces prediction and duplicate is idempotent");
s.ObserveSnapshot(4);Check(!s.HistoryComplete&&!s.CapturesComplete,"Snapshot gap is explicit instead of fabricating history");
s.Restore(new[]{new MatchStatistics.Entry("1",1,Team.Black,"Qxa1",true,false,PieceKind.Rook)},1,true,true);
Check(s.HistoryComplete&&s.CapturedBy(Team.Black).Single()==PieceKind.Rook,"Authoritative recovery replaces all prior statistics");
revision=s.Revision;
s.Restore(new[]{new MatchStatistics.Entry("1",1,Team.Black,"Qxa1",true,false,PieceKind.Rook)},1,true,true);
Check(s.Revision==revision,"Repeated heartbeat does not rebuild unchanged journal");
Check(MatchStatistics.TryClassicCapture("4k3/8/8/3pP3/8/8/8/4K3 w - d6 0 1","e5","d6",out var actor,out var capture)&&actor==Team.White&&capture==PieceKind.Pawn,"En passant records the adjacent pawn");
Check(!MatchStatistics.TryClassicCapture("4k3/8/8/3pP3/8/8/8/4K3 w - - 0 1","e5","d6",out _,out _),"Absent en-passant right cannot fabricate a capture");
Check(MatchStatistics.TryClassicCapture("4k3/P7/8/8/8/8/8/4K3 w - - 0 1","a7","a8",out _,out capture)&&capture==null,"Promotion without capture never invents a lost pawn");
Check(MatchStatistics.TryClassicCapture("1r2k3/P7/8/8/8/8/8/4K3 w - - 0 1","a7","b8",out _,out capture)&&capture==PieceKind.Rook,"Capture promotion keeps captured kind");
Check(!MatchStatistics.TryClassicCapture("bad","e2","e4",out _,out _),"Malformed history cannot claim complete captures");
s.Reset();Check(s.Entries.Count==0&&s.ConfirmedMoveNumber==0&&s.HistoryComplete,"New match resets previous lifecycle");
Console.WriteLine($"{checks} statistics checks passed.");
