// Generated by tools/generate_menu_artwork_bounds.py. Do not hand edit.
using System.Collections.Generic;
using UnityEngine;

public static class MenuArtworkBounds
{
    private static readonly Dictionary<string, Vector4> Bounds = new Dictionary<string, Vector4>
    {
        { "Assets/Materials/Gacha_menu/BackButton.png", new Vector4(0.027149321f, 0.132653061f, 0.932126697f, 0.755102041f) },
        { "Assets/Materials/Gacha_menu/BackGacha.png", new Vector4(0.248006380f, 0.315789474f, 0.494417863f, 0.465709729f) },
        { "Assets/Materials/Gacha_menu/DiamondGacha.png", new Vector4(0.107274401f, 0.132596685f, 0.779926335f, 0.723756906f) },
        { "Assets/Materials/Gacha_menu/DiamondPR.png", new Vector4(0.228867624f, 0.228867624f, 0.541467305f, 0.561403509f) },
        { "Assets/Materials/Gacha_menu/GachaMenuDesign.png", new Vector4(0.000000000f, 0.000000000f, 1.000000000f, 1.000000000f) },
        { "Assets/Materials/Gacha_menu/GachaMenuDesignBlank.png", new Vector4(0.000000000f, 0.000000000f, 1.000000000f, 1.000000000f) },
        { "Assets/Materials/Gacha_menu/GachaResultBlank.png", new Vector4(0.000000000f, 0.000000000f, 1.000000000f, 1.000000000f) },
        { "Assets/Materials/Gacha_menu/GachaResultDesign.png", new Vector4(0.000000000f, 0.000000000f, 1.000000000f, 1.000000000f) },
        { "Assets/Materials/Gacha_menu/GachaRevealCardFrame.png", new Vector4(0.054687500f, 0.041176471f, 0.890625000f, 0.917647059f) },
        { "Assets/Materials/Gacha_menu/GachaRevealGlyph1.png", new Vector4(0.050000000f, 0.050000000f, 0.906250000f, 0.906250000f) },
        { "Assets/Materials/Gacha_menu/GachaRevealGlyph2.png", new Vector4(0.050000000f, 0.050000000f, 0.906250000f, 0.906250000f) },
        { "Assets/Materials/Gacha_menu/GachaRevealGlyph3.png", new Vector4(0.050000000f, 0.050000000f, 0.906250000f, 0.906250000f) },
        { "Assets/Materials/Gacha_menu/GachaRevealGlyph4.png", new Vector4(0.050000000f, 0.050000000f, 0.906250000f, 0.906250000f) },
        { "Assets/Materials/Gacha_menu/GachaRevealGlyph5.png", new Vector4(0.050000000f, 0.050000000f, 0.906250000f, 0.906250000f) },
        { "Assets/Materials/Gacha_menu/GachaRevealGlyph6.png", new Vector4(0.050000000f, 0.050000000f, 0.906250000f, 0.906250000f) },
        { "Assets/Materials/Gacha_menu/GachaRevealRay.png", new Vector4(0.024739583f, 0.024739583f, 0.951822917f, 0.951822917f) },
        { "Assets/Materials/Gacha_menu/GachaRevealRing.png", new Vector4(0.066406250f, 0.066406250f, 0.869140625f, 0.869140625f) },
        { "Assets/Materials/Gacha_menu/GachaRevealSpark.png", new Vector4(0.046875000f, 0.046875000f, 0.914062500f, 0.914062500f) },
        { "Assets/Materials/Gacha_menu/GachaTitle.png", new Vector4(0.040071770f, 0.205100956f, 0.928827751f, 0.591923486f) },
        { "Assets/Materials/Gacha_menu/GoldGacha.png", new Vector4(0.190147330f, 0.227900552f, 0.631215470f, 0.553867403f) },
        { "Assets/Materials/Gacha_menu/GoldPR.png", new Vector4(0.228070175f, 0.222488038f, 0.536682616f, 0.580542265f) },
        { "Assets/Materials/Gacha_menu/HistoryButton.png", new Vector4(0.252762431f, 0.302486188f, 0.500920810f, 0.462707182f) },
        { "Assets/Materials/Gacha_menu/PityGacha.png", new Vector4(0.115331492f, 0.222836096f, 0.769337017f, 0.593001842f) },
        { "Assets/Materials/Gacha_menu/Skin5StarPR.png", new Vector4(0.186602871f, 0.215311005f, 0.629186603f, 0.626794258f) },
        { "Assets/Materials/Gacha_menu/StandardGacha.png", new Vector4(0.160681400f, 0.121546961f, 0.686464088f, 0.725138122f) },
        { "Assets/Materials/Gacha_menu/SummonTicket.png", new Vector4(0.168047882f, 0.082872928f, 0.659760589f, 0.796961326f) },
        { "Assets/Materials/Gacha_menu/SummonTicketPR.png", new Vector4(0.227272727f, 0.224880383f, 0.545454545f, 0.546251994f) },
        { "Assets/Materials/Gacha_menu/SummonX1.png", new Vector4(0.097005208f, 0.208984375f, 0.810546875f, 0.554687500f) },
        { "Assets/Materials/Gacha_menu/SummonX10.png", new Vector4(0.093750000f, 0.273437500f, 0.817708333f, 0.489257812f) },
        { "Assets/Materials/PlayerProfile/AchievementTitle.png", new Vector4(0.103591160f, 0.313075506f, 0.827348066f, 0.402394107f) },
        { "Assets/Materials/PlayerProfile/Avatar0.png", new Vector4(0.074218750f, 0.065843621f, 0.876953125f, 0.862139918f) },
        { "Assets/Materials/PlayerProfile/Avatar1.png", new Vector4(0.106060606f, 0.111642743f, 0.787878788f, 0.799043062f) },
        { "Assets/Materials/PlayerProfile/Avatar2.png", new Vector4(0.047846890f, 0.059011164f, 0.900318979f, 0.895534290f) },
        { "Assets/Materials/PlayerProfile/Avatar3.png", new Vector4(0.000000000f, 0.000000000f, 0.914673046f, 0.955342903f) },
        { "Assets/Materials/PlayerProfile/Avatar4.png", new Vector4(0.086921850f, 0.091706539f, 0.826953748f, 0.828548644f) },
        { "Assets/Materials/PlayerProfile/Avatar5.png", new Vector4(0.067783094f, 0.071770335f, 0.862838915f, 0.870813397f) },
        { "Assets/Materials/PlayerProfile/Back.png", new Vector4(0.167127072f, 0.218232044f, 0.666666667f, 0.577348066f) },
        { "Assets/Materials/PlayerProfile/BasicProfileData.png", new Vector4(0.045454545f, 0.221041445f, 0.910885167f, 0.632306057f) },
        { "Assets/Materials/PlayerProfile/ChangeDataProfileButton.png", new Vector4(0.016129032f, 0.045454545f, 0.972580645f, 0.914772727f) },
        { "Assets/Materials/PlayerProfile/MatchHistory.png", new Vector4(0.031946956f, 0.068565401f, 0.937914406f, 0.886075949f) },
        { "Assets/Materials/PlayerProfile/PlayerProfileMain.png", new Vector4(0.013755981f, 0.018065887f, 0.974282297f, 0.963868225f) },
        { "Assets/Materials/PlayerProfile/PlayerProfileMainBlank.png", new Vector4(0.013755981f, 0.018065887f, 0.974282297f, 0.963868225f) },
        { "Assets/Materials/PlayerProfile/PlayerProfileSketch.png", new Vector4(0.000000000f, 0.000000000f, 1.000000000f, 1.000000000f) },
        { "Assets/Materials/PlayerProfile/Streaks.png", new Vector4(0.173046252f, 0.173046252f, 0.657097289f, 0.686602871f) },
        { "Assets/Materials/LANUI/BackButton.png", new Vector4(0.101519337f, 0.286372007f, 0.802486188f, 0.453038674f) },
        { "Assets/Materials/LANUI/CopyIcon.png", new Vector4(0.313397129f, 0.312599681f, 0.362041467f, 0.405901116f) },
        { "Assets/Materials/LANUI/HostButton.png", new Vector4(0.168508287f, 0.311233886f, 0.665055249f, 0.385819521f) },
        { "Assets/Materials/LANUI/JoinButton.png", new Vector4(0.135359116f, 0.380294659f, 0.717541436f, 0.291896869f) },
        { "Assets/Materials/LANUI/LANUIBlank.png", new Vector4(0.000000000f, 0.000000000f, 1.000000000f, 1.000000000f) },
        { "Assets/Materials/LANUI/LANUIDesign.png", new Vector4(0.000000000f, 0.000000000f, 1.000000000f, 1.000000000f) },
        { "Assets/Materials/LANUI/LeaveButton.png", new Vector4(0.148480663f, 0.332412523f, 0.708563536f, 0.408839779f) },
        { "Assets/Materials/LANUI/ReadyButton.png", new Vector4(0.093232044f, 0.271639042f, 0.812154696f, 0.454880295f) },
        { "Assets/Materials/LANUI/RefreshButton.png", new Vector4(0.173342541f, 0.332412523f, 0.654005525f, 0.337937385f) },
        { "Assets/Materials/LANUI/StartButton.png", new Vector4(0.101519337f, 0.290976059f, 0.799033149f, 0.488029466f) },
        { "Assets/Materials/MultiplayerUI/BackButton.png", new Vector4(0.174953959f, 0.100828729f, 0.651933702f, 0.758287293f) },
        { "Assets/Materials/MultiplayerUI/CopyIcon.png", new Vector4(0.313397129f, 0.312599681f, 0.362041467f, 0.405901116f) },
        { "Assets/Materials/MultiplayerUI/CreateRoomButton.png", new Vector4(0.131215470f, 0.049723757f, 0.740791897f, 0.821823204f) },
        { "Assets/Materials/MultiplayerUI/JoinRoomButton.png", new Vector4(0.136740331f, 0.226519337f, 0.724677716f, 0.560773481f) },
        { "Assets/Materials/MultiplayerUI/LeaveRoomButton.png", new Vector4(0.124309392f, 0.139502762f, 0.750460405f, 0.700276243f) },
        { "Assets/Materials/MultiplayerUI/MultiplayerUIBlank.png", new Vector4(0.000000000f, 0.000000000f, 1.000000000f, 1.000000000f) },
        { "Assets/Materials/MultiplayerUI/MultiplayerUIDesign.png", new Vector4(0.000000000f, 0.000000000f, 1.000000000f, 1.000000000f) },
        { "Assets/Materials/MultiplayerUI/ReadyButton.png", new Vector4(0.134898711f, 0.058011050f, 0.730202578f, 0.830110497f) },
        { "Assets/Materials/MultiplayerUI/RefreshButton.png", new Vector4(0.137661142f, 0.145027624f, 0.725598527f, 0.689226519f) },
        { "Assets/Materials/MultiplayerUI/StartGameButton.png", new Vector4(0.082412523f, 0.127071823f, 0.835635359f, 0.747237569f) },
    };

    public static Rect GetRect(string path, Texture2D texture)
    {
        if (!Bounds.TryGetValue(path, out Vector4 b)) return new Rect(0, 0, texture.width, texture.height);
        return new Rect(b.x * texture.width, b.y * texture.height, b.z * texture.width, b.w * texture.height);
    }
}
